Fix Cancel Payment flow + Fix Mollie Client bug
mollie/commercetools-connector pull request #24
Opened 2024-08-01 17:05 UTC by NghiaDTr

2024-08-02 03:31 UTC, Tung-Huynh-Shopmacher requested changes

2024-08-02 03:31 UTC, Tung-Huynh-Shopmacher commented on processor/src/mollie/payment.mollie.ts
> +      errorMessage = `SCTM - cancelPayment - Failed to cancel payments with unknown errors`;
wrong message

2024-08-02 03:31 UTC, Tung-Huynh-Shopmacher commented on processor/src/service/payment.service.ts
> -    errorPrefix,
if we do not use the errorPrefix, remove it

2024-08-02 03:31 UTC, Tung-Huynh-Shopmacher commented on processor/src/validators/payment.validators.ts
> +  // TODO: Temporary comment out to test the Cancel Payment flow
what happened here?

2024-08-02 03:33 UTC, Tung-Huynh-Shopmacher requested changes

2024-08-02 03:33 UTC, Tung-Huynh-Shopmacher commented on processor/src/mollie/payment.mollie.ts
> +    delete paymentParams.include;
is this necessary? since we removed the nullable properties before this step

2024-08-02 04:23 UTC, NghiaDTr commented on processor/src/service/payment.service.ts
> -    errorPrefix,
Yes, we are not using any more in this place, I just remove it

2024-08-02 04:24 UTC, NghiaDTr commented on processor/src/mollie/payment.mollie.ts
> +      errorMessage = `SCTM - cancelPayment - Failed to cancel payments with unknown errors`;
I fixed the message

2024-08-02 04:31 UTC, NghiaDTr commented on processor/src/validators/payment.validators.ts
> +  // TODO: Temporary comment out to test the Cancel Payment flow
I want to use the creditcard method since it is the only method that can be used with captureMode: manual
And at that time, I thought that we did not support toggle on/off the card component yet (which will require cardToken in custom field)
But now I just saw the [merged request](https://github.com/mollie/commercetools-connector/pull/23) from Win, and I updated it

2024-08-02 04:32 UTC, NghiaDTr commented on processor/src/mollie/payment.mollie.ts
> +    delete paymentParams.include;
Yes, you are right, this logic was added before adding the function to remove empty properties out of the payload. I removed this logic

2024-08-02 04:53 UTC, Tung-Huynh-Shopmacher requested changes

2024-08-02 04:53 UTC, Tung-Huynh-Shopmacher commented on processor/src/mollie/payment.mollie.ts
> +    // const response = await initMollieClient().payments.cancel(paymentId);
remove debug

2024-08-02 04:53 UTC, Tung-Huynh-Shopmacher commented on processor/src/service/payment.service.ts
> +  action: DeterminePaymentActionType,
will we still use `action` here?

2024-08-02 09:54 UTC, NghiaDTr commented on processor/src/service/payment.service.ts
> +  action: DeterminePaymentActionType,
No, we don't. I removed it

2024-08-02 09:54 UTC, NghiaDTr commented on processor/src/mollie/payment.mollie.ts
> +    // const response = await initMollieClient().payments.cancel(paymentId);
Yes

2024-08-05 03:02 UTC, Tung-Huynh-Shopmacher approved these changes

2024-08-05 03:02 UTC, merged