Feature/mol 438/pict 252
mollie/commercetools-connector pull request #71
Opened 2024-10-02 11:55 UTC by tdang1-shopmacher

2024-10-03 03:33 UTC, tdang1-shopmacher commented on application/src/components/welcome/welcome.tsx
The 'FetchAndUpdateMethods' function makes the dependencies of useEffect Hook (at line 127) change on every render. Move it inside the useEffect callback. Alternatively, wrap the definition of 'FetchAndUpdateMethods' in its own useCallback() Hook.eslintreact-hooks/exhaustive-deps

2024-10-07 02:29 UTC, Tung-Huynh-Shopmacher requested changes

2024-10-07 02:29 UTC, Tung-Huynh-Shopmacher commented on processor/src/service/payment.service.ts
> +          !!configObjects.find((config) => config.key === method.id && config.value.status === 'Active') &&
what if I disable payment A on custom app and payment A is active on Mollie, will it appear here?

2024-10-07 03:34 UTC, tdang1-shopmacher commented on processor/src/service/payment.service.ts
> +          !!configObjects.find((config) => config.key === method.id && config.value.status === 'Active') &&
Payment A will not be visible

2024-10-07 03:36 UTC, Tung-Huynh-Shopmacher approved these changes

2024-10-07 04:29 UTC, merged