MOL-451: CA - Surcharge transaction cost
mollie/commercetools-connector pull request #94
Opened 2024-11-12 02:41 UTC by NghiaDTr

2024-11-12 08:53 UTC, Tung-Huynh-Shopmacher requested changes

2024-11-12 08:53 UTC, Tung-Huynh-Shopmacher commented on processor/src/service/payment.service.ts
> +  const cartUpdateActions = createCartUpdateActions(cart, ctPayment, surchargeAmount);
How about failed/canceled payment flow @NghiaDTr

2024-11-14 03:52 UTC, NghiaDTr commented on processor/src/service/payment.service.ts
> +  const cartUpdateActions = createCartUpdateActions(cart, ctPayment, surchargeAmount);
I added it

2024-11-15 06:42 UTC, Tung-Huynh-Shopmacher approved these changes

2024-11-19 03:24 UTC, merged